# set base image name
FROM ubuntu

# Dockerfile author/maintainer
MAINTAINER Hitesh <hitr9831@gmail.com>

# Copy testfile.sh into home directory
COPY testfile.sh home/

# Run this command when container is running
CMD ["sh", "home/testfile.sh"]

